# Generated by Django 5.0 on 2024-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_news', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('titre', models.CharField(max_length=500)),
                ('text', models.TextField()),
            ],
        ),
    ]
